# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PianoForte(object):
    def setupUi(self, PianoForte):
        PianoForte.setObjectName("PianoForte")
        PianoForte.resize(161, 130)
        PianoForte.setStyleSheet("background: url(C:\\Users\\mares\\PycharmProjects\\PianoForte\\res\\images\\wood.jpg)")
        self.Cbutton = QtWidgets.QPushButton(PianoForte)
        self.Cbutton.setGeometry(QtCore.QRect(10, 10, 21, 111))
        font = QtGui.QFont()
        font.setKerning(True)
        self.Cbutton.setFont(font)
        self.Cbutton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Cbutton.setObjectName("Cbutton")
        self.Dbutton = QtWidgets.QPushButton(PianoForte)
        self.Dbutton.setGeometry(QtCore.QRect(30, 10, 21, 111))
        self.Dbutton.setObjectName("Dbutton")
        self.Ebutton = QtWidgets.QPushButton(PianoForte)
        self.Ebutton.setGeometry(QtCore.QRect(50, 10, 21, 111))
        self.Ebutton.setObjectName("Ebutton")
        self.Fbutton = QtWidgets.QPushButton(PianoForte)
        self.Fbutton.setGeometry(QtCore.QRect(70, 10, 21, 111))
        self.Fbutton.setObjectName("Fbutton")
        self.Gbutton = QtWidgets.QPushButton(PianoForte)
        self.Gbutton.setGeometry(QtCore.QRect(90, 10, 21, 111))
        self.Gbutton.setObjectName("Gbutton")
        self.Abutton = QtWidgets.QPushButton(PianoForte)
        self.Abutton.setGeometry(QtCore.QRect(110, 10, 21, 111))
        self.Abutton.setObjectName("Abutton")
        self.Bbutton = QtWidgets.QPushButton(PianoForte)
        self.Bbutton.setGeometry(QtCore.QRect(130, 10, 21, 111))
        self.Bbutton.setObjectName("Bbutton")
        self.Gsbutton = QtWidgets.QPushButton(PianoForte)
        self.Gsbutton.setGeometry(QtCore.QRect(100, 10, 16, 51))
        self.Gsbutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Gsbutton.setObjectName("Gsbutton")
        self.Csbutton = QtWidgets.QPushButton(PianoForte)
        self.Csbutton.setGeometry(QtCore.QRect(20, 10, 16, 51))
        self.Csbutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Csbutton.setObjectName("Csbutton")
        self.Dsbutton = QtWidgets.QPushButton(PianoForte)
        self.Dsbutton.setGeometry(QtCore.QRect(40, 10, 16, 51))
        self.Dsbutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Dsbutton.setObjectName("Dsbutton")
        self.Fsbutton = QtWidgets.QPushButton(PianoForte)
        self.Fsbutton.setGeometry(QtCore.QRect(80, 10, 16, 51))
        self.Fsbutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Fsbutton.setObjectName("Fsbutton")
        self.Asbutton = QtWidgets.QPushButton(PianoForte)
        self.Asbutton.setGeometry(QtCore.QRect(120, 10, 16, 51))
        self.Asbutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Asbutton.setObjectName("Asbutton")

        self.retranslateUi(PianoForte)
        QtCore.QMetaObject.connectSlotsByName(PianoForte)

    def retranslateUi(self, PianoForte):
        _translate = QtCore.QCoreApplication.translate
        PianoForte.setWindowTitle(_translate("PianoForte", "PianoForte"))
        self.Cbutton.setText(_translate("PianoForte", "A"))
        self.Dbutton.setText(_translate("PianoForte", "S"))
        self.Ebutton.setText(_translate("PianoForte", "D"))
        self.Fbutton.setText(_translate("PianoForte", "F"))
        self.Gbutton.setText(_translate("PianoForte", "G"))
        self.Abutton.setText(_translate("PianoForte", "H"))
        self.Bbutton.setText(_translate("PianoForte", "J"))
        self.Gsbutton.setText(_translate("PianoForte", "Y"))
        self.Csbutton.setText(_translate("PianoForte", "W"))
        self.Dsbutton.setText(_translate("PianoForte", "E"))
        self.Fsbutton.setText(_translate("PianoForte", "T"))
        self.Asbutton.setText(_translate("PianoForte", "U"))
